on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: |
        cd get-malaysia-rainfall && pip install --platform manylinux2014_aarch64 --target=. --implementation cp --python-version 3.13 --only-binary=:all: --upgrade -r requirements.txt && zip -r deployment.zip .

    - name: default deploy
      uses: appleboy/lambda-action@v0.2.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: get-malaysia-rainfall
        zip_file: get-malaysia-rainfall/deployment.zip
